name: End-to-End Tests

on:
  push:
    branches:
      - add/github-actions-for-tests
    paths-ignore:
      - '**.md'
#  push:
#    branches: [master]
#    paths-ignore:
#    - '**.md'

jobs:
  E2E_Tests:
    name: End to end tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
#      matrix:
#        wp_version: [1, 2, 3, 4]


    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Get correct C lib for Nodegit
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes install libkrb5-dev
          
      - name: Npm install and build
        run: |
          npm ci
          FORCE_REDUCED_MOTION=true npm run build
#      - name: E2E Tests (WP 5.6 with Gutenberg plugin)
#        env:
#          WOOCOMMERCE_BLOCKS_PHASE: 3
#          E2E_TESTS: 1
#          GUTENBERG_LATEST: true
#          WP_VERSION: 5.6-branch
#        run: |
#          export PATH="$HOME/.composer/vendor/bin:$PATH"
#          if [[ ! -z "$E2E_TESTS" ]]; then
#            composer install --no-dev
#            npm ci
#            if [[ ! -z "$GUTENBERG_LATEST" ]]; then
#              JSON='{"config": { "SCRIPT_DEBUG": false, "JETPACK_AUTOLOAD_DEV": true } }'
#            else
#              JSON='{"core": "WordPress/WordPress#'"$WP_VERSION"'", "config": { "SCRIPT_DEBUG": false, "JETPACK_AUTOLOAD_DEV": true } }'
#            fi
#            echo $JSON > .wp-env.override.json
#            npm run build:e2e-test
#            sudo chmod -R 767 ./
#            sudo chmod -R 767 /home/runner/wp-env/
#            npm run wp-env start
#          fi
#          npm run wp-env run tests-cli "wp plugin install gutenberg --activate"
#          npm install @wordpress/e2e-test-utils@latest
#          sudo chmod -R 767 ./
#          sudo chmod -R 767 /home/runner/wp-env/
#          npm run test:e2e
#
#      - name: E2E Tests (WP 5.6)
#        env:
#          WOOCOMMERCE_BLOCKS_PHASE: 3
#          E2E_TESTS: 1
#          WP_VERSION: 5.6-branch
#        run: |
#          export PATH="$HOME/.composer/vendor/bin:$PATH"
#          if [[ ! -z "$E2E_TESTS" ]]; then
#            composer install --no-dev
#            npm ci
#            if [[ ! -z "$GUTENBERG_LATEST" ]]; then
#              JSON='{"config": { "SCRIPT_DEBUG": false, "JETPACK_AUTOLOAD_DEV": true } }'
#            else
#              JSON='{"core": "WordPress/WordPress#'"$WP_VERSION"'", "config": { "SCRIPT_DEBUG": false, "JETPACK_AUTOLOAD_DEV": true } }'
#            fi
#            echo $JSON > .wp-env.override.json
#            npm run build:e2e-test
#            sudo chmod -R 767 ./
#            sudo chmod -R 767 /home/runner/wp-env/
#            npm run wp-env start
#          fi
#          npm install @wordpress/e2e-test-utils@latest
#          sudo chmod -R 767 ./
#          sudo chmod -R 767 /home/runner/wp-env/
#          npm run test:e2e

      - name: E2E Tests (WP 5.5)
        env:
          WOOCOMMERCE_BLOCKS_PHASE: 3
          E2E_TESTS: 1
          WP_VERSION: 5.5-branch
        run: |
          export PATH="$HOME/.composer/vendor/bin:$PATH"
          if [[ ! -z "$E2E_TESTS" ]]; then
            composer install --no-dev
            npm ci
            if [[ ! -z "$GUTENBERG_LATEST" ]]; then
              JSON='{"config": { "SCRIPT_DEBUG": false, "JETPACK_AUTOLOAD_DEV": true } }'
            else
              JSON='{"core": "WordPress/WordPress#'"$WP_VERSION"'", "config": { "SCRIPT_DEBUG": false, "JETPACK_AUTOLOAD_DEV": true } }'
            fi
            echo $JSON > .wp-env.override.json
            npm run build:e2e-test
            sudo chmod -R 767 ./
            sudo chmod -R 767 /home/runner/wp-env/
            npm run wp-env start
          fi
          sudo chmod -R 767 ./
          sudo chmod -R 767 /home/runner/wp-env/
          npm run test:e2e

      - name: E2E Tests (WP 5.4)
        env:
          WOOCOMMERCE_BLOCKS_PHASE: 3
          E2E_TESTS: 1
          WP_VERSION: 5.4-branch
        run: |
          if [[ ! -z "$E2E_TESTS" ]]; then
            composer install --no-dev
            npm ci
            if [[ ! -z "$GUTENBERG_LATEST" ]]; then
              JSON='{"config": { "SCRIPT_DEBUG": false, "JETPACK_AUTOLOAD_DEV": true } }'
            else
              JSON='{"core": "WordPress/WordPress#'"$WP_VERSION"'", "config": { "SCRIPT_DEBUG": false, "JETPACK_AUTOLOAD_DEV": true } }'
            fi
            echo $JSON > .wp-env.override.json
            npm run build:e2e-test
            sudo chmod -R 767 ./
            sudo chmod -R 767 /home/runner/wp-env/
            npm run wp-env start
          fi
          sudo chmod -R 767 ./
          sudo chmod -R 767 /home/runner/wp-env/
          npm run test:e2e    

      - name: Archive debug artifacts (screenshots, HTML snapshots)
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: failures-artifacts
          path: artifacts
