name: End-to-End Tests

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  E2E_Tests:
    name: End to end tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer
            
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Npm install and build
        run: |
          npm ci
          FORCE_REDUCED_MOTION=true npm run build:e2e-test
          
      - name: Composer install
        run: |
          composer install
          
      - name: Run PHP tests
        run: |
          npm run phpunit
          
      - name: JS Unit Tests
        run: |
          npm run test

      - name: E2E Tests (WP 5.6 with Gutenberg plugin)
        env:
          WOOCOMMERCE_BLOCKS_PHASE: 3
          WP_VERSION: 5.6-branch
        run: |
          sudo chmod -R 767 ./
          npm run wp-env start
          npm run wp-env clean all
          sudo chmod -R 767 /home/runner/wp-env/
          npm run wp-env run tests-cli "wp plugin install gutenberg --activate"
          npm run test:e2e   

      - name: E2E Tests (WP 5.6)
        env:
          WOOCOMMERCE_BLOCKS_PHASE: 3
          WP_VERSION: 5.6-branch
        run: |
          JSON='{"core": "WordPress/WordPress#'"$WP_VERSION"'"}'
          echo $JSON > .wp-env.override.json
          sudo chmod -R 767 ./
          npm run wp-env start
          sudo chmod -R 767 /home/runner/wp-env/
          npm run wp-env clean all
          npm run test:e2e

      - name: E2E Tests (WP 5.5)
        env:
          WOOCOMMERCE_BLOCKS_PHASE: 3
          WP_VERSION: 5.5-branch
        run: |
          JSON='{"core": "WordPress/WordPress#'"$WP_VERSION"'"}'
          echo $JSON > .wp-env.override.json
          sudo chmod -R 767 ./
          sudo chmod -R 767 /home/runner/wp-env/
          npm run wp-env start
          npm run wp-env clean all
          npm run test:e2e

      - name: E2E Tests (WP 5.4)
        env:
          WOOCOMMERCE_BLOCKS_PHASE: 3
          WP_VERSION: 5.4-branch
        run: |
          JSON='{"core": "WordPress/WordPress#'"$WP_VERSION"'"}'
          echo $JSON > .wp-env.override.json
          sudo chmod -R 767 ./
          sudo chmod -R 767 /home/runner/wp-env/
          npm run wp-env start
          npm run wp-env clean all
          npm run test:e2e
